[project]
name = "s-expression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
se = "se:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = ["hypothesis>=6.112.4", "pytest-cov>=5.0.0", "pytest>=8.3.3"]

[tool.pytest.ini_options]
minversion = "6.0" # Set the minimum pytest version
addopts = [
    "--strict-markers",
    "--tb=short",
    "--verbosity=4",
    "--cov=src/",
    "--cov-report=xml",
]
testpaths = ["tests/"]
